### ISSUE TITLE
recover unwanted record for nested attributes

### ISSUE THREAD

**Issue by umairmunir40** [expectedbehavior/acts_as_archival#12]
Hi,
        Any model that have nested attributes it also recovers unwanted record from model.
        Suppose we have three nested attributes associated with some item in model. When I 
         - archive that item then recover it
         - destroy one of three nested attributes and make it archive  
         - after recovering that archived item it recovers all three nested attributes instead of recovering two(last updated state of an item) 
  Please help me with this issue...........

**Comment by janxious** [comment]
Let me see if I understand this correctly.
```ruby
 class Tiger
   acts_as_archival
   has_many :bears
   has_many :zebras
   accepts_nested_attributes_for :bears, :zebras
 end
 
 class Bear
   acts_as_archival
   belongs_to :tiger
 end
 
 class Zebra
   acts_as_archival
   belongs_to :zebra
 end
 
 tiger.bears.first.archive
 tiger.archive
 tiger.unarchive
 
 tiger.bears.first.archived? # => now is incorrectly false?
```

Does this match what you're seeing?

**Comment by umairmunir40** [comment]
In view suppose i have such kind of relation........
Tiger1 has
Bear 1
Bear 2
Zebra 1
Zebra 2

Then "Zebra 2" is removed from "Tiger 1" and "Tiger 1" is archived.....
when i recover "Tiger 1" from archived it shows

Bear 1
Bear 2
Zebra 1
Zebra 2 (which should be deleted as in previous state)

**Comment by janxious** [comment]
When you say "removed" and "deleted" above, are you saying those records are being removed from the db, or they are being archived using acts_as_archival stuff? Do you have another soft-delete library in your app?

**Comment by janxious** [comment]
So far, I think [this test](https://github.com/expectedbehavior/acts_as_archival/blob/master/test/associations_test.rb#L70) covers the case you are describing, so just need a little more information. :)

**Comment by umairmunir40** [comment]
yeah this issue was due to soft delete...thanks...

**Comment by janxious** [comment]
Cool! Let me know if you run into any other issues with acts_as_archival. :+1:
