### ISSUE TITLE
Deprecation warning on NOR usage regarding Rails 6.1

### ISSUE THREAD

**Issue by jasonlor** [expectedbehavior/acts_as_archival#45]
Just wanted to file an issue on this deprecation warning.

DEPRECATION WARNING: NOT conditions will no longer behave as NOR in Rails 6.1. To continue using NOR conditions, NOT each conditions manually (`.where.not(:archived_at => ...).where.not(:archive_number => ...)`). (called from irb_binding at (irb):8)

Thanks!

**Comment by janxious** [comment]
There is a fix committed here: https://github.com/expectedbehavior/acts_as_archival/commit/a0bb86040b5351460ba5588612f06889cb73642e

We have not yet cut a release for it, though.

**Comment by rakshassa** [comment]
Do you have an estimated released date for this fix?

**Comment by dbastin** [comment]
I believe this can be closed as it is now released under [2.0.0](https://github.com/expectedbehavior/acts_as_archival/tree/v2.0.0).

**Comment by esquivalient** [comment]
Yep, that's right.
