### ISSUE TITLE
Deprecation warning in Rails 6.1 for archive!

### ISSUE THREAD

**Issue by rakshassa** [expectedbehavior/acts_as_archival#46]
Rails has deprecated using return, break and throw to exit a transaction.
Since the archive! method uses execute_archival_action where you "return" from inside a transaction, every usage of archive! will result in a Deprecation warning.

To fix, simply return the function result outside the transaction in the execute_archival_action method.

**Comment by dbastin** [comment]
#48

**Comment by esquivalient** [comment]
Fixed by #48
